main/devicepkg-dev: add test for uefi.config.j2 (MR 4689)
We can't make tests for mainline.config.j2 because it is going to be
modified a lot in the future and maintaining testdata would be crazy.
On the other hand, uefi.config.j2 is pretty small and uses the same
way of checking version and architecture, so testing this file should
be enough as long as we do the same approach in other config.

[ci:skip-build] already built successfully in CI

diff --git a/main/devicepkg-dev/APKBUILD b/main/devicepkg-dev/APKBUILD
--- a/main/devicepkg-dev/APKBUILD
+++ b/main/devicepkg-dev/APKBUILD
@@ -1,10 +1,11 @@
 pkgname=devicepkg-dev
-pkgver=0.19.4
+pkgver=0.19.5
 pkgrel=0
 pkgdesc="Provides default device package functions"
 url="https://postmarketos.org"
 arch="noarch"
 license="MIT"
+makedepends="jinja2-cli"
 subpackages="$pkgname-jinja2:_jinja2"
 source="
 	compiler-gcc.h
@@ -22,6 +23,10 @@ source="
 	testdata/deviceinfo
 	testdata/expected-deviceinfo-downstream
 	testdata/expected-deviceinfo-mainline
+	testdata/expected-uefi-config-arm
+	testdata/expected-uefi-config-arm64
+	testdata/expected-uefi-config-arm64-pre-6.1.0
+	testdata/expected-uefi-config-x86_64
 "
 
 check() {
@@ -58,6 +63,68 @@ check() {
 		"$srcdir/expected-deviceinfo-mainline";
 	then
 		echo "ERROR: mainline deviceinfo contains incorrect data"
+	fi
+
+	_template="$srcdir/uefi.config.j2"
+
+	# Generate uefi config on 6.6.0 arm
+	# (no CONFIG_EFI_ZBOOT, no CONFIG_EFI_MIXED)
+	jinja2 --strict \
+		-D kernel_version="6" \
+		-D kernel_patchlevel="6" \
+		-D arch="arm" \
+		"$_template" > "$testdir/uefi-config-arm"
+
+	# Generate uefi config on 6.6.0 arm64
+	# (CONFIG_EFI_ZBOOT, no CONFIG_EFI_MIXED)
+	jinja2 --strict \
+		-D kernel_version="6" \
+		-D kernel_patchlevel="6" \
+		-D arch="arm64" \
+		"$_template" > "$testdir/uefi-config-arm64"
+
+	# Generate uefi config on 5.15.0 arm64
+	# (no CONFIG_EFI_ZBOOT, no CONFIG_EFI_MIXED)
+	jinja2 --strict \
+		-D kernel_version="5" \
+		-D kernel_patchlevel="15" \
+		-D arch="$_carch" \
+		"$_template" > "$testdir/uefi-config-arm64-pre-6.1.0"
+
+	# Generate uefi config on 6.6.0 x86_64
+	# (no CONFIG_EFI_ZBOOT, CONFIG_EFI_MIXED)
+	jinja2 --strict \
+		-D kernel_version="6" \
+		-D kernel_patchlevel="6" \
+		-D arch="x86_64" \
+		"$_template" > "$testdir/uefi-config-x86_64"
+
+	if ! cmp -s "$srcdir/expected-uefi-config-arm" \
+		"$testdir/uefi-config-arm"
+	then
+		echo "ERROR: unexpected result with uefi config on arm using 6.6.0 version"
+		exit 1
+	fi
+
+	if ! cmp -s "$srcdir/expected-uefi-config-arm64" \
+		"$testdir/uefi-config-arm64"
+	then
+		echo "ERROR: unexpected result with uefi config on arm64 using 6.6.0 version"
+		exit 1
+	fi
+
+	if ! cmp -s "$srcdir/expected-uefi-config-arm64-pre-6.1.0" \
+		"$testdir/uefi-config-arm64-pre-6.1.0"
+	then
+		echo "ERROR: unexpected result with uefi config on arm64 using 5.15.0 version"
+		exit 1
+	fi
+
+	if ! cmp -s "$srcdir/expected-uefi-config-x86_64" \
+		"$testdir/uefi-config-x86_64"
+	then
+		echo "ERROR: unexpected result with uefi config on x86_64 using 6.6.0 version"
+		exit 1
 	fi
 
 	# Cleanup
@@ -115,4 +182,8 @@ b9e64582d8c4ed35116002388b58ee62531b8db5de3f4629980ca5dcc9f39ba2c1c7c7a9caa03438
 f09cb34626f2aedf9ffa69a8050500d54291c416f5e8c8d67ce72244e1d906b190d84a3fadccd7d82824b6a68d981ca8a197a053804df1103457ddb7892b2cc9  deviceinfo
 136247a16ec91dc0c7241eeddb28c2196ae3b29946a9bc7e9566f848491ef1c53b12d05bf2dbc1cc352986712fd76f25c1510bcc8f301af540a2f01c33b299e1  expected-deviceinfo-downstream
 b2e87ab10c116adc18e89ebf478b08904b9a73b17176c03068f8711dac6353e6ab4b3fdaf4051eda05660cac31514520756973ec43d052ba9f42cb1ec9375c5d  expected-deviceinfo-mainline
+c75c157bd7fe05662be7fe24d00f8603ddc4a760f5589463ae4ea2a594430e700835ba2b6edd6b540be5c131fcfc8717556c17a1fdbc41583926787bb09709bd  expected-uefi-config-arm
+22406d611d716d32482ee3b46080d7b945ac3e0e4083bdddfa7a1eca4e9733332118a90739f4ded6e2eee01abe213c95408d9e10fbf087e19d46907bbc21bc7e  expected-uefi-config-arm64
+c75c157bd7fe05662be7fe24d00f8603ddc4a760f5589463ae4ea2a594430e700835ba2b6edd6b540be5c131fcfc8717556c17a1fdbc41583926787bb09709bd  expected-uefi-config-arm64-pre-6.1.0
+3d3ca6a614e7114a9e45c307be42245550030cc8d5d8c7a7e9130cb5da8c5a6b6a641fa9f33c41a4a9ec3dd9158b4a03b00ef2bbae233b255200d91400498e06  expected-uefi-config-x86_64
 "
